apiVersion: apps/v1
kind: Deployment
metadata:
  name: harpokratos
  labels:
    app: harpokratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harpokratos
  template:
    metadata:
      labels:
        app: harpokratos
        release: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: PORT
              value: "5000"
          image: "harpokratos:latest"
          name: harpokratos
          ports:
            - containerPort: 5000