apiVersion: v1
kind: Service
metadata:
  name: golangexamplesidecar-service
spec:
  selector:
    app: golangexamplesidecar-service
  ports:
    - name: "http"
      port:  {{ .Values.envVariables.golangexample.port }}
      targetPort: {{ .Values.envVariables.golangexample.port }}