apiVersion: v1
kind: Service
metadata:
  name: golangexampleapi-service
spec:
  selector:
    app: golangexampleapi
  ports:
    - name: "http"
      port:  {{ .Values.envVariables.golangexample.port }}
      targetPort: {{ .Values.envVariables.golangexample.port }}