apiVersion: v1
kind: Service
metadata:
  name: harpokratos-service
spec:
  selector:
    app: harpokratos
  ports:
    - name: "http"
      port:  {{ .Values.envVariables.harpokratos.port }}
      targetPort: {{ .Values.envVariables.harpokratos.port }}